//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseHoldManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EarnedAmount
    {
        public int EarnedAmountId { get; set; }
        public System.DateTime EarnedAmountDate { get; set; }
        public string EarnedAmountSource { get; set; }
        public int AmountEarned { get; set; }
        public string EarnedAmountDetails { get; set; }
    }
}
